import React from 'react';
import { Link } from 'react-router-dom';

const Section = ({ title, children }) => (
  <div style={{ marginBottom: 28 }}>
    <h3 style={{
      color: '#a5b4fc', fontSize: '0.95rem', fontWeight: 700,
      marginBottom: 10, fontFamily: 'Inter, sans-serif',
      letterSpacing: '-0.01em',
    }}>
      {title}
    </h3>
    <div style={{
      color: 'var(--muted)', fontSize: '0.875rem',
      lineHeight: 1.8, fontFamily: 'Inter, sans-serif',
    }}>
      {children}
    </div>
  </div>
);

const PageShell = ({ title, emoji, children }) => (
  <div style={{ minHeight: '100vh', padding: '100px 6vw 60px', maxWidth: 760, margin: '0 auto' }}>
    <Link to="/" style={{
      color: '#a5b4fc', textDecoration: 'none', fontSize: '0.82rem',
      display: 'inline-flex', alignItems: 'center', gap: 6,
      marginBottom: 28, fontFamily: 'Inter, sans-serif', fontWeight: 600,
      transition: 'color 0.15s',
    }}>
      ← Back to Home
    </Link>
    <h1 style={{
      fontFamily: 'Playfair Display, serif',
      fontSize: 'clamp(1.8rem,4vw,2.4rem)',
      color: 'var(--white)', fontWeight: 900,
      marginBottom: 6, letterSpacing: '-0.03em',
    }}>
      {emoji} {title}
    </h1>
    <p style={{
      color: 'var(--gray)', fontSize: '0.78rem',
      marginBottom: 40, fontFamily: 'Inter, sans-serif',
    }}>
      Last updated: January 2025
    </p>
    <div style={{
      background: 'var(--card)', border: '1px solid var(--border)',
      borderRadius: 18, padding: '32px 28px',
    }}>
      {children}
    </div>
  </div>
);

export const PrivacyPolicy = () => (
  <PageShell title="Privacy Policy" emoji="🔒">
    <Section title="1. Information We Collect">
      We collect information you provide directly: name, email address, phone number when you create an account.
      We also collect usage data like destinations searched, trips planned, and features used to improve our service.
    </Section>
    <Section title="2. How We Use Your Information">
      <ul style={{ paddingLeft: 18, margin: 0 }}>
        <li>To generate personalized AI travel itineraries</li>
        <li>To send trip plans to your email and WhatsApp</li>
        <li>To save your trip history and preferences</li>
        <li>To improve our AI models and features</li>
        <li>To send important service updates (not spam)</li>
      </ul>
    </Section>
    <Section title="3. Data Storage & Security">
      Your data is stored securely on MongoDB Atlas (encrypted at rest). We use JWT tokens for authentication.
      We never sell your personal data to third parties. API keys and passwords are never stored in plain text.
    </Section>
    <Section title="4. Third-Party Services">
      We use: Google Gemini AI (trip generation), OpenWeatherMap (weather data), ExchangeRate API (currency),
      Razorpay (payments). Each has their own privacy policy.
    </Section>
    <Section title="5. Cookies">
      We use essential cookies for authentication and localStorage for saving your preferences
      (theme, wishlist, packing list). You can clear these anytime from your browser settings.
    </Section>
    <Section title="6. Your Rights">
      You can request deletion of your account and data by emailing us.
      You can update your profile information anytime from your account settings.
    </Section>
    <Section title="7. Contact">
      For privacy concerns:{' '}
      <a href="mailto:abhinaygour59@gmail.com" style={{ color: '#a5b4fc', textDecoration: 'none' }}>
        abhinaygour59@gmail.com
      </a>
    </Section>
  </PageShell>
);

export const TermsOfService = () => (
  <PageShell title="Terms of Service" emoji="📄">
    <Section title="1. Acceptance of Terms">
      By using AI Travel Planner, you agree to these terms. If you disagree, please do not use our service.
    </Section>
    <Section title="2. Use of Service">
      <ul style={{ paddingLeft: 18, margin: 0 }}>
        <li>You must be 13+ years old to use this service</li>
        <li>One account per person — no sharing credentials</li>
        <li>Do not use the service for illegal activities</li>
        <li>AI-generated itineraries are suggestions, not guarantees</li>
      </ul>
    </Section>
    <Section title="3. AI-Generated Content">
      Trip plans are generated by AI and may contain inaccuracies. Always verify prices, timings, and
      availability before booking. We are not responsible for any losses due to reliance on AI-generated content.
    </Section>
    <Section title="4. Payments">
      Payments are processed securely via Razorpay. Subscription fees are non-refundable unless there is a
      technical error on our part. Contact us within 7 days for refund requests.
    </Section>
    <Section title="5. Intellectual Property">
      AI Travel Planner and its content are owned by us. You may not copy, reproduce, or distribute our
      platform without permission.
    </Section>
    <Section title="6. Limitation of Liability">
      We provide the service "as is". We are not liable for travel disruptions, booking failures, or any
      indirect damages arising from use of our platform.
    </Section>
    <Section title="7. Changes to Terms">
      We may update these terms. Continued use after changes means acceptance of new terms.
    </Section>
    <Section title="8. Contact">
      Questions? Email:{' '}
      <a href="mailto:abhinaygour59@gmail.com" style={{ color: '#a5b4fc', textDecoration: 'none' }}>
        abhinaygour59@gmail.com
      </a>
    </Section>
  </PageShell>
);
