// Auto-send Email Service
export const sendEmailDirectly = async (userEmail, userName, tripData) => {
  try {
    console.log('📧 Preparing email for:', userEmail);
    
    // Simplified email content without complex URLs
    const emailContent = `Dear ${userName},

Your AI Travel Plan is Ready!

🌟 DESTINATION: ${tripData.destination}
📅 DURATION: ${tripData.duration}
📆 DATES: ${tripData.dates}

✨ OVERVIEW:
${tripData.overview}

🎯 HIGHLIGHTS:
${tripData.highlights?.map(h => `• ${h}`).join('\n') || 'Amazing experiences await!'}

💰 BUDGET: ${tripData.budgetEstimate?.total || 'Budget details included'}

📋 DAILY ITINERARY:
${tripData.dailyItinerary ? tripData.dailyItinerary.slice(0, 3).map(day => 
  `DAY ${day.day} - ${day.title}\n${day.activities?.slice(0, 2).map(act => 
    `  ${act.time}: ${act.activity} at ${act.location}`
  ).join('\n') || 'Activities planned'}`
).join('\n\n') : 'Detailed itinerary included'}

🧳 TRAVEL TIPS:
${tripData.travelTips?.map(tip => `• ${tip}`).join('\n') || 'Expert tips included'}

Have an amazing trip!
AI Travel Planner Team`;

    // Simple subject and clean mailto
    const subject = `Your AI Travel Plan for ${tripData.destination}`;
    const mailtoLink = `mailto:${userEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(emailContent)}`;
    
    // Use location.href instead of window.open to prevent popup issues
    try {
      window.location.href = mailtoLink;
    } catch (e) {
      // Fallback: try window.open
      window.open(mailtoLink);
    }
    
    console.log('✅ Email client opened for:', userEmail);
    
    return { success: true, message: 'Email opened successfully' };
    
  } catch (error) {
    console.error('❌ Email error:', error);
    return { success: false, message: 'Email failed: ' + error.message };
  }
};

// Auto-send WhatsApp Service
export const sendWhatsAppDirectly = async (phoneNumber, userName, tripData) => {
  try {
    console.log('📱 Preparing WhatsApp for:', phoneNumber);
    
    // Format WhatsApp message (shorter for mobile)
    const whatsappMessage = `🌟 *${tripData.destination} Travel Plan Ready!* 🌟

Hi ${userName}! Your personalized ${tripData.duration} trip is ready:

📅 *Dates:* ${tripData.dates}

✨ *Overview:*
${tripData.overview?.substring(0, 200)}...

🎯 *Top Highlights:*
${tripData.highlights?.slice(0, 4).map(h => `• ${h}`).join('\n') || 'Amazing experiences planned!'}

💰 *Budget:* ${tripData.budgetEstimate?.total || 'Details in email'}

📋 *Day 1 Preview:*
${tripData.dailyItinerary?.[0] ? 
  `*${tripData.dailyItinerary[0].title}*\n${tripData.dailyItinerary[0].activities?.slice(0, 2).map(act => 
    `${act.time} - ${act.activity}`
  ).join('\n') || 'Activities planned'}` : 'Detailed itinerary in email'}

📧 *Complete details sent to your email!*

🎒 Ready for an amazing adventure?

Generated by AI Travel Planner ✈️`;

    // Clean phone number
    const cleanPhone = phoneNumber.replace(/[^0-9+]/g, '');
    
    // Create WhatsApp URL
    const whatsappUrl = `https://wa.me/${cleanPhone}?text=${encodeURIComponent(whatsappMessage)}`;
    
    // Open WhatsApp immediately after email
    setTimeout(() => {
      window.open(whatsappUrl, '_blank');
      console.log('✅ WhatsApp opened for:', cleanPhone);
    }, 1500);
    
    return { success: true, message: 'WhatsApp opened successfully' };
    
  } catch (error) {
    console.error('❌ WhatsApp error:', error);
    return { success: false, message: 'WhatsApp failed: ' + error.message };
  }
};

// Auto-send both Email and WhatsApp when trip is ready
export const sendTripPlanDirectly = async (user, tripData) => {
  try {
    console.log('🚀 AUTO-SENDING trip plan to:', user.email, user.phone);
    
    // Show immediate notification
    showAutoSendNotification();
    
    // Send email immediately (no delay)
    const emailResult = await sendEmailDirectly(user.email, user.name, tripData);
    console.log('Email result:', emailResult);
    
    // Send WhatsApp after short delay
    const whatsappResult = await sendWhatsAppDirectly(user.phone, user.name, tripData);
    console.log('WhatsApp result:', whatsappResult);
    
    return {
      success: true,
      email: emailResult,
      whatsapp: whatsappResult,
      message: 'Trip plan sent to email and WhatsApp!'
    };
    
  } catch (error) {
    console.error('❌ Auto-send error:', error);
    return {
      success: false,
      message: 'Auto-send failed: ' + error.message
    };
  }
};

// Show notification that auto-sending is happening
export const showAutoSendNotification = () => {
  // Create notification element
  const notification = document.createElement('div');
  notification.style.cssText = `
    position: fixed;
    top: 20px;
    right: 20px;
    background: linear-gradient(135deg, #f43f5e, #9f1239);
    color: white;
    padding: 16px 20px;
    border-radius: 12px;
    box-shadow: 0 8px 32px rgba(244,63,94,0.4);
    z-index: 10000;
    font-family: 'DM Sans', sans-serif;
    font-size: 14px;
    font-weight: 600;
    max-width: 320px;
    animation: slideInRight 0.3s ease;
  `;
  
  notification.innerHTML = `
    <div style="display: flex; align-items: center; gap: 10px;">
      <span style="font-size: 20px;">🎉</span>
      <div>
        <div style="font-weight: 700;">Trip Plan Ready!</div>
        <div style="font-size: 12px; opacity: 0.9; margin-top: 4px;">
          📧 Opening Email Client...<br>
          📱 Opening WhatsApp...
        </div>
      </div>
    </div>
  `;
  
  // Add animation keyframes if not exists
  if (!document.querySelector('#autoSendAnimation')) {
    const style = document.createElement('style');
    style.id = 'autoSendAnimation';
    style.textContent = `
      @keyframes slideInRight {
        from { transform: translateX(100%); opacity: 0; }
        to { transform: translateX(0); opacity: 1; }
      }
    `;
    document.head.appendChild(style);
  }
  
  document.body.appendChild(notification);
  
  // Remove notification after 6 seconds
  setTimeout(() => {
    if (notification.parentNode) {
      notification.style.animation = 'slideInRight 0.3s ease reverse';
      setTimeout(() => notification.remove(), 300);
    }
  }, 6000);
};