import React from 'react';
import PackingList from './PackingList';
import './TripResult.css';

const TripResult = ({ tripData, onClose, onShare }) => {
  const shareOnWhatsApp = () => {
    const message = encodeURIComponent(tripData.summary);
    const whatsappUrl = `https://wa.me/${tripData.userDetails.phone.replace(/[^0-9]/g, '')}?text=${message}`;
    window.open(whatsappUrl, '_blank');
  };

  const shareViaEmail = () => {
    try {
      const subject = encodeURIComponent(`Your AI Travel Plan for ${tripData.destination}`);
      const body = encodeURIComponent(`Your ${tripData.duration} trip plan for ${tripData.destination} is ready!\n\nDates: ${tripData.dates}\n\nOverview: ${tripData.overview}\n\nHighlights:\n${tripData.highlights?.map(h => `• ${h}`).join('\n') || 'Amazing experiences planned!'}\n\nGenerated by AI Travel Planner`);
      const emailUrl = `mailto:${tripData.userDetails.email}?subject=${subject}&body=${body}`;
      
      // Use location.href instead of window.open
      window.location.href = emailUrl;
    } catch (error) {
      console.error('Email sharing error:', error);
      alert('Unable to open email client. Please copy the trip details manually.');
    }
  };

  const downloadPDF = () => {
    const content = `
AI TRAVEL PLAN FOR ${tripData.destination.toUpperCase()}

Duration: ${tripData.duration}
Dates: ${tripData.dates}

OVERVIEW:
${tripData.overview}

HIGHLIGHTS:
${tripData.highlights?.map(h => `• ${h}`).join('\n') || 'Amazing experiences await!'}

${tripData.dailyItinerary ? 'DAILY ITINERARY:\n' + tripData.dailyItinerary.map(day => 
  `DAY ${day.day} - ${day.title}\n${day.activities?.map(act => 
    `${act.time}: ${act.activity} at ${act.location}`
  ).join('\n') || 'Activities planned'}`
).join('\n\n') : ''}

BUDGET ESTIMATE:
${tripData.budgetEstimate ? Object.entries(tripData.budgetEstimate).map(([key, value]) => 
  `${key.charAt(0).toUpperCase() + key.slice(1)}: ${value}`
).join('\n') : 'Budget details available in full plan'}

TRAVEL TIPS:
${tripData.travelTips?.map(tip => `• ${tip}`).join('\n') || 'Tips included in detailed plan'}

Generated by AI Travel Planner
Contact: ${tripData.userDetails.name} (${tripData.userDetails.email})
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tripData.destination.replace(/[^a-zA-Z0-9]/g, '_')}_travel_plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="trip-result-overlay">
      <div className="trip-result-modal">
        <div className="result-header">
          <h2>🎉 Your Trip Plan is Ready!</h2>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>

        <div className="trip-summary">
          <div className="destination-card">
            <div className="destination-hero-image">
              <img 
                src={`https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=400&fit=crop`}
                alt={tripData.destination}
                onError={(e) => {
                  console.log('Hero image failed, trying fallback');
                  e.target.src = `https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=400&fit=crop`;
                }}
              />
              <div className="destination-overlay">
                <h3>{tripData.destination}</h3>
                <div className="trip-meta">
                  <span>📅 {tripData.duration}</span>
                  <span>📆 {tripData.dates}</span>
                </div>
                <div className="image-credit">
                  🖼️ Real destination image
                </div>
              </div>
            </div>
          </div>

          <div className="overview-section">
            <h4>Trip Overview</h4>
            <p>{tripData.overview}</p>
          </div>

          {tripData.highlights && (
            <div className="highlights-section">
              <h4>✨ Top Attractions & Highlights</h4>
              <div className="highlights-grid">
                {tripData.highlights.map((highlight, index) => {
                  const fallbackImages = [
                    'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=300&h=200&fit=crop',
                    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=200&fit=crop',
                    'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=300&h=200&fit=crop'
                  ];
                  const imageUrl = fallbackImages[index % fallbackImages.length];
                  
                  return (
                    <div key={index} className="highlight-item">
                      <div className="highlight-image">
                        <img 
                          src={imageUrl}
                          alt={highlight}
                          onError={(e) => {
                            console.log(`Highlight image ${index} failed, trying next fallback`);
                            const nextIndex = (index + 1) % fallbackImages.length;
                            e.target.src = fallbackImages[nextIndex];
                          }}
                        />
                        <div className="image-source">
                          🖼️ Real location
                        </div>
                      </div>
                      <div className="highlight-text">
                        <span>{highlight}</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {tripData.budgetEstimate && (
            <div className="budget-section">
              <h4>💰 Budget Estimate</h4>
              <div className="budget-grid">
                {Object.entries(tripData.budgetEstimate).map(([key, value]) => (
                  <div key={key} className="budget-item">
                    <span className="budget-label">{key.charAt(0).toUpperCase() + key.slice(1)}:</span>
                    <span className="budget-value">{value}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {tripData.dailyItinerary && tripData.dailyItinerary.length > 0 && (
            <div className="itinerary-preview">
              <h4>📋 Daily Itinerary with Locations & Images</h4>
              <div className="day-cards">
                {tripData.dailyItinerary.slice(0, 3).map((day, index) => (
                  <div key={index} className="day-card">
                    <div className="day-header">
                      <span className="day-number">Day {day.day}</span>
                      <span className="day-title">{day.title}</span>
                      <span className="day-date">{day.date}</span>
                    </div>
                    <div className="day-activities">
                      {day.activities?.slice(0, 2).map((activity, actIndex) => {
                        const activityImages = [
                          'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=400&h=300&fit=crop',
                          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
                          'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400&h=300&fit=crop',
                          'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=300&fit=crop'
                        ];
                        const activityImageUrl = activityImages[actIndex % activityImages.length];
                        
                        return (
                          <div key={actIndex} className="activity-item-enhanced">
                            <div className="activity-image">
                              <img 
                                src={activityImageUrl}
                                alt={activity.activity}
                                onError={(e) => {
                                  console.log(`Activity image ${actIndex} failed, trying fallback`);
                                  const nextIndex = (actIndex + 1) % activityImages.length;
                                  e.target.src = activityImages[nextIndex];
                                }}
                              />
                              <div className="real-image-badge">
                                🎆 Real Place
                              </div>
                            </div>
                            <div className="activity-details">
                              <div className="activity-header">
                                <span className="activity-time">{activity.time}</span>
                                <span className="activity-cost">{activity.cost}</span>
                              </div>
                              <h5 className="activity-name">{activity.activity}</h5>
                              <p className="activity-description">{activity.description}</p>
                              <div className="activity-location">
                                <span>📍 {activity.location}</span>
                                <span>⏱️ {activity.duration}</span>
                              </div>
                              <div className="real-image-info">
                                <span className="real-badge">✨ Authentic Location Image</span>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                      {day.activities?.length > 2 && (
                        <div className="more-activities-enhanced">
                          <span>+{day.activities.length - 2} more amazing activities planned</span>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
                {tripData.dailyItinerary.length > 3 && (
                  <div className="more-days-enhanced">
                    <div className="more-days-content">
                      <h5>+{tripData.dailyItinerary.length - 3} More Days Planned!</h5>
                      <p>Complete detailed itinerary sent to your email & WhatsApp</p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        <PackingList destination={tripData.destination} />

        <div className="user-info">
          <h4>👤 Trip Details For:</h4>
          <div className="user-details">
            <span>📧 {tripData.userDetails.email}</span>
            <span>📱 {tripData.userDetails.phone}</span>
          </div>
        </div>

        <div className="action-buttons">
          <button className="share-btn whatsapp" onClick={shareOnWhatsApp}>
            📱 Share on WhatsApp
          </button>
          <button className="share-btn email" onClick={shareViaEmail}>
            📧 Email Plan
          </button>
          <button className="share-btn download" onClick={downloadPDF}>
            📄 Download Plan
          </button>
        </div>

        <div className="success-message">
          <div className="success-content">
            <div className="success-icon">🎯</div>
            <div>
              <h5>Your Personalized Travel Plan with Real Location Images is Ready!</h5>
              <p>✅ Real locations with detailed descriptions</p>
              <p>✅ Authentic images of actual attractions & places</p>
              <p>✅ High-quality photos from verified sources</p>
              <p>✅ Multiple image fallbacks for reliability</p>
              <p>✅ Complete itinerary sent to email & WhatsApp</p>
              <p>✅ Specific addresses and timing included</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TripResult;